# Generated by Django 5.2.4 on 2025-07-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('club', models.CharField(max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('position', models.CharField(choices=[('GOAL-KEEPER', 'Goal keeper'), ('DEFENDER', 'Defender'), ('MIDFIELDER', 'Midfielder'), ('FORWARD', 'Forward')], default='GOAL-KEEPER', max_length=20)),
                ('height', models.DecimalField(decimal_places=1, max_digits=3)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=20)),
                ('is_academy', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
