# Generated by Django 5.2.4 on 2025-07-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
